version: '3.7'

services:
  app:
    build: ./app
    restart: always
    volumes:
      - ./app:/app
    ports:
      - 8011:8011

  client:
    build: ./client
    restart: always
    volumes:
      - ./client:/client
      - /client/node_modules
    depends_on:
      - app
    links:
      - app
    ports:
      - 8080:8080